### ISSUE TITLE
Discussions section

### ISSUE THREAD

**Issue by vault-thirteen** [ByteWelder/Decktility#1]
Hello there !

I have always been thinking about a portable pocket PC (or a PDA, as they were called several years ago) having a power supply of several 18650 batteries. Me personally thinks that a lot of people are interested in your project as well as me. It would be great to add a `Discussions` section to your repository to allow people to discuss the **Decktility**.

Thank you for what you are doing.

**Comment by KenVanHoeylandt** [comment]
Thank you for your interest and for the suggestion. I didn't know of that feature until your message. I've activated it on the project.
